/* Name: Collin Heretick
    Class: CSET 1200
    Instructor: Dr. Jared Oluoch
    Programming Assignment: Course Project
    Date: 10/01/20
    Summary: This program implements a class which creates an array representing the annual salaries for five of
        UT's CSET professors over the past ten years, where the first dimension holds the professors' names and the
        second dimension holds their randomly generated salaries.

This code is my own work. I did not get any help from any online source
such as chegg.com; from a classmate, or any other person other than the instructor
or TA for this course. I understand that getting outside help from this course
other than from the instructor or TA will result in a grade of 0 in this
assignment and other disciplinary actions for academic dishonesty. */

package Project;

public class Project {
    public static void main(String[] args) {
        // Initialize ProfessorsSalaries object
        ProfessorsSalaries professorsSalaries = new ProfessorsSalaries(5, 10);

        // This method prints the data generated by ProfessorsSalaries
        professorsSalaries.print();

        // This method returns the index of the professor who made the lowest salary over ten years
        System.out.println("The index of the professor that made the lowest salary over ten years is index "
                + professorsSalaries.lowestSalary()+ " which represents Professor "
                + (professorsSalaries.lowestSalary() + 1));


        // This method returns the average salary made by all professors over ten years
        System.out.printf("The average salary made by all of the professors over ten years is $%,.2f\n",
                professorsSalaries.average());

        // This method returns the year in which the lowest salary was earned
        System.out.println("The year in which the lowest salary was earned was year "
                + professorsSalaries.lowestSalaryYear());

        // This method returns the total amount of money earned by all five professors over ten years
        System.out.printf("The total amount of money made by all of the professors, over ten years, is $%,.2f",
                professorsSalaries.total());

        // This method prints each professor's total pay
        //professorsSalaries.professorsSalaryTotals();
    }
}

